AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String

Resources:
  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn

  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Join ["/", ["/aws", "lambda", !Ref MainFunction]]
      FilterPattern: '{$.level = "error"}'
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Sub ${AWS::StackName}
          MetricName: ErrorMetricFilter

  EmailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: kai.hendry+ltabus@gmail.com

  LogAlarmResource:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ErrorLogs
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ErrorMetricFilter
      Namespace: !Sub ${AWS::StackName}
      Threshold: 1
      Period: 60
      Statistic: Average
      TreatMissingData: breaching
      AlarmActions:
        - !Ref EmailSNSTopic
    DependsOn: EmailSNSTopic

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ltabus
      Architectures:
        - arm64
      CodeUri: .
      Handler: main
      Runtime: provided.al2
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          accountkey: "{{resolve:ssm:/ltabus/accountkey:1}}"
    Metadata:
      BuildMethod: makefile

Outputs:
  GatewayEndPoint:
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
